dyn_o_mite:
  datacenter: ppcc_dc_ptk_lab
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - cgr-lab-hfa-01:28101:rack1:ppcc_dc_hfa_lab:3221225471
  dyn_seed_provider: simple_provider
  listen: 0.0.0.0:8102
  servers:
  - redis:6379:1
  tokens: '3221225471'
  secure_server_option: none
  data_store: 0
  stats_listen: 0.0.0.0:22222