dyn_o_mite:
  datacenter: prepaid_dc_hfa
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - prepaid-01-ptk:8101:rack1:prepaid_dc_ptk:3221225471
  dyn_seed_provider: simple_provider
  listen: 0.0.0.0:8102
  servers:
  - redis:6379:1
  tokens: '3221225471'
  secure_server_option: none
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22222