dyn_o_mite:
  datacenter: ppcc_dc_hfa
  rack: rack1
  dyn_listen: 0.0.0.0:8101
  dyn_seeds:
  - ppcc-cgr-ptk-node-01:8101:rack1:ppcc_dc_ptk:3221225471
  dyn_seed_provider: simple_provider
  listen: 0.0.0.0:8102
  servers:
  - 127.0.0.1:22122:1
  tokens: '3221225471'
  secure_server_option: datacenter
  pem_key_file: conf/dynomite.pem
  data_store: 0
  stats_listen: 0.0.0.0:22222